# Generated by Django 5.1.3 on 2024-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_cost', models.IntegerField()),
                ('asset_specs', models.TextField()),
                ('asset_category', models.CharField(max_length=50)),
                ('asset_img', models.ImageField(upload_to='Product/')),
                ('asset_qty', models.IntegerField()),
            ],
        ),
    ]
