# Generated by Django 5.1.3 on 2024-11-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_asset_cost_asset_inventory_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Inventory_value',
            new_name='inv_value',
        ),
    ]
