# Generated by Django 5.1.3 on 2024-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_asset_asset_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_no', models.CharField(max_length=50)),
                ('staff_fname', models.CharField(max_length=100)),
                ('staff_sname', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_specs', models.TextField()),
                ('asset_category', models.CharField(max_length=50)),
                ('asset_qty', models.IntegerField()),
            ],
        ),
    ]
