# Generated by Django 5.1.3 on 2024-12-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='status',
            new_name='allocation_status',
        ),
    ]
