# Generated by Django 5.1.3 on 2024-12-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='allocation_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
