# Generated by Django 5.1.3 on 2024-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_asset_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_staff',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='staff_no',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
