# Generated by Django 5.1.3 on 2024-12-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_asset_assigned_staff_asset_staff_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='assigned_staff',
            new_name='Staff',
        ),
    ]
