# Generated by Django 5.1.3 on 2024-12-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_rename_assigned_staff_asset_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='staff_no',
        ),
    ]
